---
# 📁 Hyun's Code collection (Pytorch) 
---

### <h3 align="right">🥇 Authored by <strong>Hyun</strong></h3>

# ✏️  What is **Pytorch**?

- Python 기반의 deep learning framework
- tensor란 array, matrices와 비슷한 special data structure이다.

# ✏️ Importing Libraries

In [36]:
import torch
import numpy as np
import torch, torchvision

# ✏️  Methods and Examples

## 🔎 Basic Methods

- **torch .tensor ( )**: tensor로 변환하기
- **torch .from_numpy ( )**: numpy array를 tensor로 바꿈
- **torch .ones_like ( )**: tensor의 shape, datatype은 유지하면서 1로 찬 tensor 생성
- **torch .rand_like ( )**: tensor의 shape, datatype은 유지하면서 random한 수로 찬 tensor 생성
- **torch .rand ( < shape > )**: shape에 맞는 random tensor를 반환
- **torch .ones ( < shape > )**: shape에 맞는 1 tensor를 반환
- **torch .zeros ( < shape > )**: shape에 맞는 0 tensor를 반환
- **torch .cat ( )**: tensor들을 합함
- **torch .mul ( )**: tensor들을 곱함
- **torch .matmul ( )**: tensor들끼리 행렬곱 연산을 시행
- **torch .add_ ( < int > )**: tensor에 정수를 더함
- **텐서 .numpy( )**: tensor를 numpy로 바꿈

### 📔 Examples

In [13]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [6]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0622, 0.0990],
        [0.1682, 0.8215]]) 



In [11]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.5373, 0.9462, 0.0152],
        [0.2210, 0.5261, 0.2530]])

In [12]:
ones_tensor = torch.ones(shape)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
zeros_tensor = torch.zeros(shape)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [24]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [29]:
data = [[1, 2],[3, 4], [5,6]]
tensor = torch.tensor(data)
print(tensor.mul(tensor))
print({tensor * tensor})

tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]])
{tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]])}


In [32]:
print(tensor.matmul(tensor.T))
# Alternative syntax:
print(tensor @ tensor.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])
tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])


In [33]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6]]) 

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])


In [35]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


## 🔎 Auto-grad

> Auto-grad
- Auto-grad는 neural network train을 도와주는 도구다.
  - Forward Propagation: 정답을 예측해나간다.
  - Backward Propagation: error에 따라 parameter를 조정한다.

- **torch .tensor ( )**: tensor로 변환하기
- **torch .from_numpy ( )**: numpy array를 tensor로 바꿈
- **torch .ones_like ( )**: tensor의 shape, datatype은 유지하면서 1로 찬 tensor 생성
- **torch .rand_like ( )**: tensor의 shape, datatype은 유지하면서 random한 수로 찬 tensor 생성
- **torch .rand ( < shape > )**: shape에 맞는 random tensor를 반환
- **torch .ones ( < shape > )**: shape에 맞는 1 tensor를 반환
- **torch .zeros ( < shape > )**: shape에 맞는 0 tensor를 반환
- **torch .cat ( )**: tensor들을 합함
- **torch .mul ( )**: tensor들을 곱함
- **torch .matmul ( )**: tensor들끼리 행렬곱 연산을 시행
- **torch .add_ ( < int > )**: tensor에 정수를 더함
- **텐서 .numpy( )**: tensor를 numpy로 바꿈

### 📔 Examples

In [37]:
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)   # single image with 3 channels, and height& & Width of 64
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /Users/junghyunwoo/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth


In [41]:
prediction = model(data) # forward propagation

loss = (prediction - labels).sum()
loss.backward() # backward propagation

optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

optim.step() # initiate gradient descent
